### ISSUE TITLE
removeFilter doesn't seem to work

### ISSUE THREAD

**Issue by krulleboll** [jmorrell/backbone-filtered-collection#1]
In my view I do this: 

this.filteredCollection.filterBy({ "LastModified": statusFilter });

The problem I have is that removeFilter doesn't work, even if I call it immediately after the previous line:

this.filteredCollection.removeFilter("LastModified");

this._filters[filterName] is undefined in the removeFilter function.

As a side note I would to also support something like this for removing a filter:

this.filteredCollection.filterBy({ "LastModified": null });

This would make for better logics in many cases (if you already decided to remove a filter on another level in your code).

Keep up the good work!

**Comment by krulleboll** [comment]
Misunderstood the usage. This works fine. Sorry.

**Comment by jmorrell** [comment]
Is there any way the docs can be updated to be clearer?

Also, it's generally a good idea to look through the tests if something appears to be broken: https://github.com/jmorrell/backbone-filtered-collection/blob/master/test/test.js

**Comment by krulleboll** [comment]
I think the docs are fine. I was trying this stuff out and I quickly just assumed it was designed to set one filter per attribute. I see that your actual design is much more flexible in cases you need to filter on more than one attribute.
