### ISSUE TITLE
Superset undefined when trying to filter an empty collection twice

### ISSUE THREAD

**Issue by pcomans** [jmorrell/backbone-filtered-collection#9]
Essentially, this will cause an exception:

```
var collection = new Backbone.Collection([]);
var a = new FilteredCollection(collection);
var b = new FilteredCollection(a);

Uncaught TypeError: Cannot read property 'toArray' of undefined
```

Fiddle is here, I pasted in the source code for 0.4.0.
Libraries used are BB 1.0, jQuery 1.7.2, underscore 1.3.3
http://jsfiddle.net/xpe1czd5/3/

**Comment by pcomans** [comment]
Could not replicate in fiddle, I apologize.

**Comment by jmorrell** [comment]
I see the error in the fiddle. Re-opening so I can make sure and take a look at it. I thought there were unit tests that checked this use case...

**Comment by pcomans** [comment]
The fiddle is broken it says var b = new FilteredCollection(b);

**Comment by jmorrell** [comment]
Ah, yeah that makes sense. JS lifts the declarations so `b` is going to get passed in as undefined in that case. Thanks for filing and providing a test case :smile: :+1:
